spring:
# 파일
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB # 전체 요청(파일 + 데이터)의 최대 크기
  thymeleaf:
    cache: false
# 데이터베이스
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:tcp://localhost/~/test
#    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
# JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
  #Security 기본
  security:
    user:
      name: user
      password: 1234
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
# JWT
jwt:
  secret: skcc-secret-key-skcc-secret-key-skcc-secret-key # 최소 32바이트 이상만 권장됨
  expiration: 1800000 # 30분
# MyBatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 테이블 컬럼 명이랑 DTO 필드명이랑 다를경우

## 로그설정
logging:
  level:
    root: info # 전체 로그 레벨
    skcc.arch: debug # 특정 패키지 레벨
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread][%highlight(%-5level)]%X{traceId}%X{signature} %X{depth}%msg%n" # 콘솔 로그 패턴
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread][%highlight(%-5level)][%X{traceId}][%X{depth}] %cyan(%logger{0,20}.%M) - %msg%n" # 콘솔 로그 패턴
#  file:
#    name: logs/app.log # 파일 로그 경로 지정
#    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n" # 파일 로그 패턴

## p6spy (운영환경에서는 false로)
decorator:
  datasource:
    p6spy:
      enable-logging: true
